name: Python Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository into the specified folder
    - name: Checkout the repository to a specific folder
      uses: actions/checkout@v2
      with:
        repository: 'Ramia-Suresh/passing_argument'  # Replace with your actual repository
        path: './my-folder'  # Path to the folder inside the workspace where the repo will be cloned

    # Step 2: List files in the cloned folder to ensure repo is checked out correctly
    - name: List files in the cloned folder
      run: ls -lrth ./my-folder  # List files in the 'my-folder' to confirm the repo is cloned correctly

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version to use in the workflow

    # Step 4: Create a virtual environment and install dependencies
    - name: Create Virtual Environment and Install Dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install --upgrade pip  # Update pip to the latest version
        pip install -r ./my-folder/my-folder/requirements.txt  # Install dependencies from the requirements.txt file

    # Step 5: Run the Python script from the cloned repo
    - name: Run Python Script
      run: |
        source venv/bin/activate  # Re-activate the virtual environment
        python ./my-folder/my-folder/my_script.py  # Run the Python script inside the virtual environment
